app = "x-downloader-kjem6q"
primary_region = "ams"

[env]
  PORT = "4455"

[http_service]
  internal_port = 4455
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[[vm]]
  size = "performance-1x"
